"use client";

export const UPDATE_DENTIST_DETAIL = "UPDATE_DENTIST_DETAIL";
export const UPDATE_PATIENT_DETAIL = "UPDATE_PATIENT_DETAIL";
export const UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL";
export const RESET_USER_DETAIL = "RESET_USER_DETAIL";
export const UPDATE_PATIENT_ID = "UPDATE_PATIENT_ID";
export const UPDATE_PATIENT_DETAIL_ERROR = "UPDATE_PATIENT_DETAIL_ERROR";
