'use client'

export const UPDATE_DENTIST_DETAIL = 'UPDATE_DENTIST_DETAIL';
export const UPDATE_PATIENT_DETAIL = 'UPDATE_PATIENT_DETAIL';
export const UPDATE_PATIENT_ID = 'UPDATE_PATIENT_ID';
export const UPDATE_PATIENT_DETAIL_ERROR = 'UPDATE_PATIENT_DETAIL_ERROR';
